version: '2'

services:

  mysql:
    image: mariadb
    volumes:
       - /Users/macbookair/Sites/WPDocker/db-data:/var/lib/mysql
    restart: always  
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: wp

  wordpress:
    depends_on:
       - mysql
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - /Users/macbookair/Sites/WPDocker/wp-content:/var/www/html/wp-content
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wp

volumes:
    db-data:
